apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: stateless
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
